### ISSUE TITLE
Friendly error message when probe not found

### ISSUE THREAD

**Issue by magowant** [tjheslin1/Patterdale#33]
If a probe name in database probes list is not defined as a probe, the following error is logged:

`Exception in thread "main" java.lang.NullPointerException
        at io.github.tjheslin1.patterdale.metrics.probe.TypeToProbeMapper.createProbe(TypeToProbeMapper.java:40)
        at io.github.tjheslin1.patterdale.Patterdale.lambda$createProbes$7(Patterdale.java:152)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at io.github.tjheslin1.patterdale.Patterdale.start(Patterdale.java:96)
        at io.github.tjheslin1.patterdale.Patterdale.main(Patterdale.java:87)` 

Please can this be updated to be a bit more friendly. e.g. ```'Probe <probeName> not defined'```

**Comment by tjheslin1** [comment]
Will do! I think Patterdale should still fail to start but in a much friendlier fashion.

**Comment by tjheslin1** [comment]
Addressed in release [1.2.4](https://github.com/tjheslin1/Patterdale/releases/tag/1.2.4)
